### PR TITLE
mac clipboard: text/plain support

### PR DESCRIPTION
**Pull request by bumfo**
A partial implementation of #51. Formats other than text/plain is not supported yet.

### CODE REVIEW

**Review by lgorence — APPROVED** [review]
Thanks for picking up on this work! 🙂

**Comment by tonsky** [comment]
Thanks! Merged as c32163c78536cb38c54c524392489ba0855727a5

**Comment by bumfo** [comment]
> Thanks! Merged as [5215c56](https://github.com/HumbleUI/JWM/commit/5215c56841dcc111de964b1359fbc3ea7bc2804d)

Thanks for fixing. I would be more careful about JNILocal the next time. ;)

**Comment by tonsky** [comment]
They are tricky—sometimes they matter, sometimes they don’t. The main purpose of them is to clean up local references in loops, but I prefer to use them everywhere just to be sure

**Pull request closed without merging**
